baseURL = 'https://rtj.dev/'
languageCode = 'en-us'
title = 'rtj.dev'
paginate = 10
theme = 'PaperMod'
enableEmoji = true
googleAnalytics = 'G-9BHN5G7N67'

[params]
env = 'production'
author = 'Roland Thomas Jr'
defaultTheme = 'auto'
ShowShareButtons = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true
ShowRssButtonInSectionTermList = true
comments = true
ShowReadingTime = true
ShowToc = false

  [params.assets]
  favicon = "/favicons/favicon.ico"
  favicon16x16 =  "/favicons/favicon-16x16.png"
  favicon32x32 =  "/favicons/favicon-32x32.png"
  apple_touch_icon =  "/favicons/apple-touch-icon.png"
  android_chrome_192x192 = "/favicons/android-chrome-192x192"
  android_chrome_512x512 = "/favicons/android-chrome-512x512"

  [params.homeInfoParams]
  Title = "Roland Thomas Jr \U0001F525"
  Content = 'Welcome to my blog'

  [[params.socialIcons]]
  name = 'github'
  url = 'https://github.com/rolandtjr'

  [[params.socialIcons]]
  name = 'codewars'
  url = 'https://www.codewars.com/users/rolandtjr'

  [[params.socialIcons]]
  name = 'leetcode'
  url = 'https://leetcode.com/rolandtjr'

  [[params.socialIcons]]
  name = 'credly'
  url = 'https://credly.com/users/roland-thomas-jr'

  [[params.socialIcons]]
  name = 'goodreads'
  url = 'https://www.goodreads.com/rolandthomasjr'

  [[params.socialIcons]]
  name = 'email'
  url = 'mailto:roland@rtj.dev'

  [[params.socialIcons]]
  name = 'Rss'
  url = 'index.xml'

[languages.en]
languageName = 'English'
weight = 1

  [languages.en.taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[[languages.en.menu.main]]
name = "Archive"
url = "archives/"
weight = 5

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 10

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[[languages.en.menu.main]]
name = "git.rtj.dev"
url = "https://git.rtj.dev"
weight = 15

[outputs]
home = [ "HTML", "RSS", "JSON" ]
