baseURL = 'https://rtj.dev/'
title = 'rtj.dev'
pagination.pagerSize = 10
theme = 'PaperMod'
enableEmoji = true
pygmentsUseClasses = true
googleAnalytics = 'G-9BHN5G7N67'

[params]
env = 'production'
author = 'Roland Thomas Jr'
defaultTheme = 'dark'
disableThemeToggle = false
ShowShareButtons = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true
ShowRssButtonInSectionTermList = true
comments = true
ShowReadingTime = true
ShowToc = false

  [params.label]
  icon = "/apple-touch-icon.png"
  text = " "
  iconHeight = 40

  [params.gitea]
  icon = "/gitea_rtj_logo.png"
  text = "git.rtj.dev"
  site = "https://git.rtj.dev"
  iconHeight = 30

  [params.assets]
  favicon = "/favicon.ico"
  favicon16x16 = "/favicon-16x16.png"
  favicon32x32 = "/favicon-32x32.png"
  apple_touch_icon = "/apple-touch-icon.png"
  android_chrome_192x192 = "/android-chrome-192x192"
  android_chrome_512x512 = "/android-chrome-512x512"

  [params.homeInfoParams]
  Title = "Roland Thomas Jr \U0001F525"
  Content = "I'm a systems-minded engineer with a focus on resilient tooling, DevSecOps automation, and CLI architecture.\n\nI build frameworks like [Falyx](https://github.com/rolandtjr/falyx) to turn complex workflows into reliable command-line experiences — in YAML or code.\n\n > “Automation should be composable, introspectable, and a pleasure to maintain."

  [[params.socialIcons]]
  name = 'github'
  url = 'https://github.com/rolandtjr'

  [[params.socialIcons]]
  name = 'linkedin'
  url = 'https://www.linkedin.com/in/roland-thomas-jr'

  [[params.socialIcons]]
  name = 'codewars'
  url = 'https://www.codewars.com/users/rolandtjr'

  [[params.socialIcons]]
  name = 'leetcode'
  url = 'https://leetcode.com/rolandtjr'

  [[params.socialIcons]]
  name = 'credly'
  url = 'https://credly.com/users/roland-thomas-jr'

  [[params.socialIcons]]
  name = 'goodreads'
  url = 'https://www.goodreads.com/rolandthomasjr'

  [[params.socialIcons]]
  name = 'email'
  url = 'mailto:roland@rtj.dev'

  [[params.socialIcons]]
  name = 'Rss'
  url = 'index.xml'

[languages]
[languages.en]
languageName = 'English'
languageCode = 'en-us'
weight = 1

  [languages.en.taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[[languages.en.menu.main]]
name = "Archive"
url = "archives/"
weight = 5

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 10

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[outputs]
home = [ "HTML", "RSS", "JSON" ]
