name: rtj.dev Build and Deploy
run-name: Build and Deploy
on: [push]

jobs:
  Build-and-Deploy:
    runs-on: docker
    defaults:
      run:
        shell: sh
    steps:
      - name: Setup node.js
        run: |
          apk --update add nodejs npm git curl
      - name: Check out repository code recursively
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Print repository name
        run: |
          echo "💡 The "${{ gitea.repository }}" repository has been cloned to the runner."
      - name: Pass login information
        run: |
          mkdir -p $HOME/.docker
          echo "${{ secrets.DOCKER_AUTH_CONFIG }}" | base64 -d > $HOME/.docker/config.json
      - name: Build Docker Image
        run: |
          cd ${{ gitea.workspace }}
          docker build -f Dockerfile -t git.rtj.dev/roland/rtj.dev:0.0.1 .
          docker push git.rtj.dev/roland/rtj.dev:0.0.1
      - name: Signal Restart
        run: |
          curl ${{OPTIONS}} ${{ secrets.API_KEY }}" ${{ secrets.ENDPOINT }}
