name: rtj.dev Build and Deploy
run-name: Build and Deploy
on: [push]

jobs:
  Build-and-Deploy:
    runs-on: docker
    steps:
      - name: Setup node.js
        run: apk --update add nodejs npm
      - run: npm ci
      - run: npm test
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ gitea.repository }} repository has been cloned to the runner."
      - name: Pass login information
        env: 
          DOCKER_AUTH_CONFIG: ${{ secrets.DOCKER_AUTH_CONFIG }}
        run: |
          docker info
          mkdir -p $HOME/.docker
          echo "$DOCKER_AUTH_CONFIG" > $HOME/.docker/config.json

      - name: Build Docker Image
        run: |
          docker build -f Dockerfile -t rtj.dev:0.0.1
          docker push rtj.dev:0.0.1
